# Generated by Django 5.1.2 on 2024-10-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='authors_to_%(app_label)s_%(class)s', to='quickstart.author'),
        ),
    ]
