# Generated by Django 5.1.2 on 2024-10-12 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quickstart', '0002_alter_article_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('authors', models.ManyToManyField(related_name='authors_to_%(app_label)s_%(class)s', to='quickstart.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_to_%(app_label)s_%(class)s', to='quickstart.category')),
            ],
            options={
                'db_table': 'blog_article',
            },
        ),
    ]
