# Generated by Django 5.1.2 on 2024-10-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_copy_data'),
        ('quickstart', '0002_alter_comment_article_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='authors_to_%(app_label)s_%(class)s', to='quickstart.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_to_%(app_label)s_%(class)s', to='quickstart.category'),
        ),
    ]
